[package]
name = "test-rs"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
libloading = "0.8"

[build-dependencies]
glob = "0.3.1"
anyhow = "1.0.71"

